### ISSUE TITLE
It doesn't work anymore

### ISSUE THREAD

**Issue by robozb** [RealZimboGuy/ewelink-api-java#4]
Ewelink changed something in their oauth login system:

```
Exception in thread "main" java.lang.Exception: Sign:oauthClient enable invalid
	at com.github.realzimboguy.ewelink.api.EweLink.login(EweLink.java:124)
	at hu.wfs.ewelinkbeci.EwelinkBeci.main(EwelinkBeci.java:17)
```

**Comment by robozb** [comment]
OH, beautiful It works again with the latest version: 2.1.3-RELEASE
Thank you so much for the developing!!!

Kind Regards

Beci
